"""Added a custom filename field to documents

Revision ID: 054ad7cc9161
Revises: ecc16f6df1c4
Create Date: 2024-01-30 13:37:53.731309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054ad7cc9161'
down_revision = 'ecc16f6df1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('custom_filename')

    # ### end Alembic commands ###
