"""Added fields to retrieve payment history

Revision ID: 244102d6e7a0
Revises: 2ab3233c22d4
Create Date: 2023-12-14 18:23:18.261967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244102d6e7a0'
down_revision = '2ab3233c22d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'])
        batch_op.drop_column('payment_type')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('square_footage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('square_footage')
        batch_op.drop_column('year_built')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
