"""Nullable Tenant fields added

Revision ID: 889061010fe6
Revises: c97d501691f2
Create Date: 2024-02-07 14:51:35.546064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889061010fe6'
down_revision = 'c97d501691f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
