"""removed circular relation between lease and payment

Revision ID: 8d397374edb7
Revises: f3225253fcca
Create Date: 2024-01-25 19:23:52.045212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d397374edb7'
down_revision = 'f3225253fcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index('ix_lease_payment_id')
        batch_op.drop_constraint('lease_payment_id_fkey', type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('lease_payment_id_fkey', 'payment', ['payment_id'], ['id'])
        batch_op.create_index('ix_lease_payment_id', ['payment_id'], unique=False)

    # ### end Alembic commands ###
