"""Added a rent class and address property to the property class

Revision ID: 981571150aa9
Revises: 2d5093cc380a
Create Date: 2023-12-13 16:14:11.139730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981571150aa9'
down_revision = '2d5093cc380a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('trash', sa.Float(), nullable=False),
    sa.Column('water_sewer', sa.Float(), nullable=False),
    sa.Column('parking', sa.Float(), nullable=False),
    sa.Column('debt', sa.Float(), nullable=False),
    sa.Column('breaks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('rent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('address')

    op.drop_table('rent')
    # ### end Alembic commands ###
