"""reverted again

Revision ID: 9f3e7215e224
Revises: 7191901f8a8e
Create Date: 2023-12-27 16:39:13.517937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3e7215e224'
down_revision = '7191901f8a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_unit_id'), ['unit_id'], unique=False)
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'])

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_unit_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_unit_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_unit_id'))
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###
